FROM ubuntu:latest

RUN apt update && apt upgrade -y && \
    apt install -y time build-essential libffi-dev libgmp-dev libncurses-dev \
        libgsl-dev liblapack-dev libblas-dev pkg-config pipx curl nodejs npm
